version: '3'

services:

  broker-service:
    build: 
      context: ./broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build: 
      context: ./authentication-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgresql-service port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    depends_on:
      - postgresql-service
      
  postgresql-service:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
